version: "3"

services:
  myapp:
    # build: .
    image: friendlyhello:v3
    container_name: myapp
    ports:
      - "5000:5000"
    environment:
      NAME: World

  redis:
    image: redis
    container_name: web
