openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://0.0.0.0:9090/v1.0

paths:
  /posts:
    post:
      summary: post
      description: post
      operationId: api.all
      responses:
        200:
          description: blog response
          content:
            text/plain:
              schema:
                type: object
